### PR TITLE
Fix #8; 1 1/2 new config-options

### LINKED ISSUE #8: bug: making one input invalid, then making another valid makes the whole form incorrectly valid
Steps to Reproduce: make 2 inputs. make both required. make the first valid, then make it invalid. then make the second valid. the whole form will show as valid.

Expected Behavior: the whole form should be invalid. I think this is likely because it's only checking changed inputs, but not persisting the previous invalid states. There should be an option to re-check every input every time, or make this the default.

### PR DESCRIPTION
**Pull request by AnthyG**
I have made multiple changes apart from just fixing #8. I hope that is okay, else I'll remove the other changes and make a separate PR or something.

List of all changes:

*   Move all field data in the store into the property `fields` (this is, to prevent from overriding `dirty` and `valid` on the form itself (I guess this makes it one property more "difficult" to manually access the generated things on the fields)
*   Renamed the config-option `stopAtFirstError` to `stopAtFirstFieldError` (it still has the same functionality)
*   Added a new config-option `stopAtFirstError` (which stops at the first error of all fields to be validated)
*   All fields now have the original data in a property `data` (to prevent overriding `errors`, `pending`, `valid` and `enabled`)
*   Added `initialFieldsData` which keeps all the fields with their original data when the form gets initialized (so a field with a default value that has been changed multiple times and then back to the default value will not be dirty) (not sure, if the original implementation actually did this, as, to be honest, I kinda lost myself in there :sweat\_smile:)
*   ~Wrapped the `afterUpdate`-do-`walkThroughFields` in a `setTimeout` to prevent an instant call after creating the form (I experienced this while using [SMUI](https://github.com/hperrin/svelte-material-ui), and I haven't tested yet, if this also happens with plain elements)~
*   Rename `oldValues` to `oldFields`
*   If the validator is async, push `name` to the field' errors instead of `rule` (which, I think would be `undefined`)
*   Rename the function `field` to `validateField`
*   I've changed the `for`\-loop in the `validateField`\-function and the `Object.keys(fields).forEach`\-loop in `walkThroughFields` to be a `some`\-loop instead (not entirely sure, if this might be bad, although I'd expect that Babel would automatically polyfill it)

In addition, as I renamed and moved a few things around, the docs will need an update, which I will be happy to do, once all the things are decided to be good or changed to be good.

Also, you might notice that I wasn't able to keep the code-style.

### CODE REVIEW

**Comment by chainlist** [comment]
Hi @AnthyG ,

Thank you for your your PR. Didn't get much time recently to work and apparently github doesn't send me notification anymore for Pull Requests. So my bad for the late answer!

Since you are introducing new behavior / new options, I'll update the package after the merge as a minor update because of no breaking change.
Agreed will all the changes you did, only thing missing as you mentioend is the documentation change. After that, I'll approve and merge your pull request.

**Comment by AnthyG** [comment]
Ok, I fixed some more bugs (and forgot to remove \`console.debug\`'s again :sweat\_smile: ) and updated the README.  
 

Just as a headsup to you saing that you'd do a "minor update because of no breaking change": I **did** move all the fields from the main "form validation object" to a sub-property `fields`. If you think this is not necessary, I'll revert that change (I myself am not sure which of the two variants is better.. tho I guess having it without another nested property would be easier (which was also your original implementation), but I also find it a bit weird of having reversed properties.. :shrug:).

**Comment by chainlist** [comment]
I agree with you. I talked too quickly with that changes.

The benefits of have an inner `fields` property containing all the fields would be to be able to not mess up with the inner property of the form such as `[valid, pending, dirty, ...]`.

It is easier to handle without any `fields` property.

That's a change that I actually like, if you are OK with that, maybe writing a warning inside the README that states that for now on, property are contained inside `fields`. 

What do you think?

**Comment by AnthyG** [comment]
Which version will it then be, so I can add the note to the README?  
1.0.2 or 1.1.0 or something else :?

**Comment by chainlist** [comment]
It will be 1.1.0

**Comment by AnthyG** [comment]
I think this also provided fixes for #4 and #6 btw.

**Pull request merged**
