### PR TITLE
Add integration tests using an example component

### PR DESCRIPTION
**Pull request by hampuslavin**
Hi!
Here's another round of tests if you're interested :) 

- Adds an integration test for the form logic.
- Adds an ExampleComponent that is used as the test subject.
- Adds a small fix so that the `errors` array is always defined (it is otherwise `undefined` in some scenarios when `stopAtFirstError` or `stopAtFirstFieldError` is used). If this is indeed intended or you don't want me to poke around in the source code, I can just add null checks in the `FormExample.svelte` component 👍 

I couldn't get the async validator test to work straight off the bat, but this should be a good start :)

### CODE REVIEW

**Comment by chainlist** [comment]
Hi @hampuslavin,

Thanks for the second round of test!

Something weird is happening, `Object.fromEntries` doesn't seem to work.
It might be an issue with node version, not sure!

**Comment by hampuslavin** [comment]
@chainlist Is this something you'd like to merge in at some point or should I close? :)

**Comment by chainlist** [comment]
Hi @hampuslavin, 

All tests are more than welcome, and thanks for yours!
I will merge this MR as soon as the conflicts are fixed :)

**Comment by hampuslavin** [comment]
@chainlist Thank for your fast reply! Now it should be good to go :) 👍

**Comment by chainlist** [comment]
And it's been merged, good job on that one!

**Pull request merged**
